### ISSUE TITLE
another static export issue.

### ISSUE THREAD

**Issue by fchengpc** [prismicio/prismic-nextjs-sample#9]
getting following error when i try to static export: related to >> https://github.com/prismicio/prismic-nextjs-sample/issues/2
```
Error: Unable to encode undefined of type undefined
    at q (.../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:10587)
    at Object.at (.../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:11859)
    at .../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:1:8656
    at x (/.../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:2:16618)
    at Generator._invoke (/.../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:2:16406)
    at Generator.e.(anonymous function) [as next] (/.../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:2:16797)
    at i (/.../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:2:11295)
    at u (/.../.next/server/static/N5tG4CAwenuzD_tK2NeDB/pages/blogHome.js:2:11489)
(node:45887) UnhandledPromiseRejectionWarning: Error: Unable to encode undefined of type undefined
    at q (/..../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:10587)
    at Object.at (/.../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:11859)
    at t.getByUID (/.../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:3961)
    at /.../node_modules/prismic-javascript/dist/prismic-javascript.min.js:1:20503
    at process._tickCallback (internal/process/next_tick.js:68:7)```

**Comment by fchengpc** [comment]
gitbyUID is an huge issue. switch everything over to query. but still unable to get the access token....

**Comment by bountyx** [comment]
Has this been fixed?
